next(null, {
    list: [{
        id: "1",
        payType: 1,
        isAutoPay: false,
        payNo: "13555555555",
        alias: "爸爸的电话"
    }, {
        id: "2",
        payType: 5,
        isAutoPay: true,
        payNo: 23423423,
        alias: "我家水费",
        accountNo: "尾号1234"
    }, {
        id: "3",
        payType: 7,
        isAutoPay: false,
        payNo: 454556432424,
        alias: "我家燃气"
    }, {
        id: "4",
        payType: 11,
        isAutoPay: true,
        payNo: 9966432,
        alias: "我家电费",
        accountNo: "尾号555666"
    }],
    code: "0000",
    message: "查询成功！"
});
